name: split_bill
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flex_color_scheme: ^8.2.0
  google_fonts: ^6.2.1
  camera: ^0.11.2
  path_provider: ^2.1.5
  path: ^1.9.1
  equatable: ^2.0.0
  flutter_gemma: ^0.10.4
  firebase_core: ^4.0.0
  firebase_ai: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
